# Generated by Django 4.1.13 on 2024-01-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
