# Generated by Django 4.1.13 on 2024-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='protocol',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
